name: Update WVU Sports Feed

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour (UTC)
  workflow_dispatch:      # allows manual trigger

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Engadget RSS feed
        run: |
          curl -s https://wvusports.com/rss -o lectures/wvu_sports.xml

      - name: Commit and push lectures/wvu_sports.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add lectures/wvu_sports.xml
          # Commit even if no changes (force update)
          git diff --cached --quiet || git commit -m "Update WVU Sports Feed"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
